name: Update Proxy List

on:
  schedule:
    - cron: '18 */4 * * *'
  push:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Bash
        run: |
          echo "ðŸ”¨ Downloading files"
          curl -sSL 'https://raw.githubusercontent.com/proxifly/free-proxy-list/main/proxies/all/data.txt' -o /tmp/proxifly.txt
          curl -sSL 'https://raw.githubusercontent.com/monosans/proxy-list/refs/heads/main/proxies/all.txt' -o /tmp/monosans.txt
          curl -sSL 'https://raw.githubusercontent.com/hookzof/socks5_list/refs/heads/master/proxy.txt' -o /tmp/hookzof.txt
          curl -sSL 'https://raw.githubusercontent.com/vakhov/fresh-proxy-list/master/socks5.txt' -o /tmp/vakhov.txt
          curl -sSL 'https://raw.githubusercontent.com/roosterkid/openproxylist/refs/heads/main/SOCKS5_RAW.txt' -o /tmp/openproxylist.txt
          curl -sSL 'https://raw.githubusercontent.com/mmpx12/proxy-list/refs/heads/master/proxies.txt' -o /tmp/mmpx12.txt
          ls -all /tmp | grep txt || true
          touch output.txt || true
          grep -v '^socks4' /tmp/proxifly.txt >> output.txt
          grep -v '^socks4' /tmp/monosans.txt >> output.txt
          sed 's/^/socks5:\/\//' /tmp/hookzof.txt >> output.txt
          sed 's/^/socks5:\/\//' /tmp/vakhov.txt >> output.txt
          sed 's/^/socks5:\/\//' /tmp/openproxylist.txt >> output.txt
          grep -v '^socks4' /tmp/mmpx12.txt >> output.txt
          # ç§»é™¤ä¸åˆè§„
          grep -E '^[a-zA-Z0-9]+://([0-9]{1,3}\.){3}[0-9]{1,3}:[0-9]+$' output.txt | tee output.txt.tmp && mv output.txt.tmp output.txt || true
          # åŽ»é‡æŽ’åº
          sort -u output.txt -o output.txt
          # è®¡æ•°
          cat output.txt | wc -l || true
          # æäº¤
          git config user.name "HelloTools-Bot"
          git config user.email "bot@932.moe"
          git fetch origin main
          echo "ðŸ”¨ Creating fresh orphan commit"
          git checkout --orphan temp-new-main
          git rm -rf --cached . > /dev/null 2>&1 || true
          git add .
          git commit -m "chore: update proxy list | $(date +'%Y-%m-%d %H:%M:%S') | $(git status --porcelain | wc -l) files [skip ci]"
          git branch -D main || true
          git branch -M temp-new-main main
          git checkout main
          git push origin main --force-with-lease
          echo "âœ… Changes pushed to repository"
